export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const API_CALL_SAMPLE_REQUEST = 'API_CALL_SAMPLE_REQUEST';
export const API_CALL_SAMPLE_SUCCESS = 'API_CALL_SAMPLE_SUCCESS';
export const API_CALL_SAMPLE_FAILURE = 'API_CALL_SAMPLE_FAILURE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const LOGIN_USER_FETCH_REQUEST = 'LOGIN_USER_FETCH_REQUEST';
export const LOGIN_USER_FETCH_SUCCESS = 'LOGIN_USER_FETCH_SUCCESS';
export const LOGIN_USER_FETCH_FAILURE = 'LOGIN_USER_FETCH_FAILURE';
export const LOGIN_AUTHORIZE_SUCCESS = 'LOGIN_AUTHORIZE_SUCCESS';

export const ORGANOGRAM_LIST_FETCH_REQUEST = 'ORGANOGRAM_LIST_FETCH_REQUEST';
export const ORGANOGRAM_LIST_FETCH_SUCCESS = 'ORGANOGRAM_LIST_FETCH_SUCCESS';
export const ORGANOGRAM_LIST_FETCH_FAILURE = 'ORGANOGRAM_LIST_FETCH_FAILURE';
export const ORGANOGRAM_STATUS_CHANGE = 'ORGANOGRAM_STATUS_CHANGE';
export const ORGANOGRAM_ADD_REQUEST = 'ORGANOGRAM_ADD_REQUEST';
export const ORGANOGRAM_ADD_SUCCESS = 'ORGANOGRAM_ADD_SUCCESS';
export const ORGANOGRAM_ADD_FAILURE = 'ORGANOGRAM_ADD_FAILURE';
